### ISSUE TITLE
SSH config file parsing is broken

### ISSUE THREAD

**Issue by NickCarneiro** [NickCarneiro/remtail#14]
Gaurav's ssh config isn't getting parsed properly. It's missing hostnames.

Something is likely wrong with the upstream ssh parsing package

```
Host ggmathur
  User gaurav
  HostName ggmathur.ausoff.indeed.net
  IdentityFile ~/.ssh/login
Host tst-user1
  User gaurav
  HostName tst-user1.indeed.net
  IdentityFile ~/.ssh/login
Host tst-user2
  User gaurav
  HostName tst-user2.indeed.net
  IdentityFile ~/.ssh/login
Host tst-svc1
  User gaurav
  HostName tst-svc1.indeed.net
  IdentityFile ~/.ssh/login
Host tst-svc2
  User gaurav
  HostName tst-svc2.indeed.net
  IdentityFile ~/.ssh/login
Host ausoff-releng1.ausoff.indeed.net
  ForwardAgent yes
```

**Comment by mjpitz** [comment]
Looks like the config parser we're using makes some brash assumptions about the ssh_config file format:  https://github.com/CrowdProcess/node-ssh-config-parser/blob/master/index.js#L15

**Comment by mjpitz** [comment]
Found a bug in the merging of credentials.  See commit above.  Pretty much, we were always taking the remtail.json file over the ssh config rather than trying to merge the two
