### ISSUE TITLE
Not working as his on windows.... but .....

### ISSUE THREAD

**Issue by UnclePhil** [NickCarneiro/remtail#4]
add the osenv libraries in the load 
     npm install osenv --save
change 2 lines
    var osenv = require('osenv');
    var DEFAULT_CREDENTIALS_LOCATION = path.join(osenv.home(), '.remtail.json');

and it work almost perfectly..

**Comment by NickCarneiro** [comment]
Bug report of the year right here. Fix published in 0.0.5. Thanks!
