### ISSUE TITLE
Generate a remtail.json

### ISSUE THREAD

**Issue by ggmathur** [NickCarneiro/remtail#6]
If I type in my user/pass, maybe save it as an ssh cred for later use.

**Comment by NickCarneiro** [comment]
Rather than save from the main workflow, let's add a flag that will take you through an interactive process to generate a remtail.json.

**Comment by mjpitz** [comment]
Should we look at adding commander support so that we can better organize the commands and flags?

**Comment by NickCarneiro** [comment]
Yes, I really like the commander .option interface. And you get help for free!

**Comment by mjpitz** [comment]
It's really clean and easy to do a subcommand approach

**Comment by NickCarneiro** [comment]
On second thought, it's irresponsible to automate saving passwords to a file.

I also want to encourage people to use native ssh configs because they're standard. Closing this. If we want to generate ssh configs that can be another issue.
