### ISSUE TITLE
Show file name with host name

### ISSUE THREAD

**Issue by ggmathur** [NickCarneiro/remtail#8]
If I'm tailing two files on the same host, it's hard to tell them apart. Figure out how the two file names differ (what part of the path) and display that.

**Comment by brunowego** [comment]
+1

**Comment by mjpitz** [comment]
Pull request up for review: #10

**Comment by mjpitz** [comment]
~~Ah, my current code doesn't support something like: tomcat1-app/logs/application.log tomcat2-app/logs/application.log.  Working on an improvement~~

Fixed this.  @ggmathur: Please check out branch jpitz and review.  Let me know if there is an improvement you'd like me to make.

**Comment by NickCarneiro** [comment]
Great implementation. This is how I would have done it.

**Comment by ggmathur** [comment]
Looks good. Thanks @jpitz!
